channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astroid=2.3.1=py36_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - bitstring=3.1.5=py36_1
  - blas=1.0=openblas
  - bleach=3.1.0=py36_0
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py36_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - flatbuffers=1.11.0=he1b5a44_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=hb3b607b_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h211956c_0
  - importlib_metadata=0.23=py36_0
  - ipykernel=5.1.2=py36h39e3cac_0
  - ipython=7.8.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.1=py36_0
  - jpeg=9b=habf39ab_1
  - jsonschema=3.0.2=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.3=py36_1
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - lazy-object-proxy=1.4.2=py36h7b6447c_0
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=12_openblas
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.1=py36h5429711_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h7b6447c_0
  - more-itertools=7.2.0=py36_0
  - nbconvert=5.6.0=py36_1
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - notebook=6.0.1=py36_0
  - numpy=1.17.2=py36h95a1406_0
  - onnx=1.6.0=py36he1b5a44_0
  - openblas=0.3.7=h6e990d7_1
  - openssl=1.1.1=h7b6447c_0
  - packaging=19.2=py_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=19.2.3=py36_0
  - pluggy=0.13.0=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.9.2=py36he1b5a44_1
  - ptyprocess=0.6.0=py36_0
  - py=1.8.0=py36_0
  - pygments=2.4.2=py_0
  - pylint=2.4.2=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h22d08a2_1
  - pyrsistent=0.15.4=py36h7b6447c_0
  - pytest=5.2.0=py36_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.2=py_0
  - pyzmq=18.1.0=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.5.5=py_0
  - readline=7.0=h7b6447c_5
  - scipy=1.3.1=py36he2b7bc3_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.2.0=py36_0
  - sip=4.19.13=py36he6710b0_0
  - six=1.12.0=py36_1000
  - sqlite=3.29.0=h7b6447c_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - typed-ast=1.4.0=py36h7b6447c_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.8.0
    - astor==0.8.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.24.0
    - h5py==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - opt-einsum==3.1.0
    - tensorboard==2.0.0
    - tensorflow-estimator==2.0.0
    - tensorflow-gpu==2.0.0
    - termcolor==1.1.0
    - werkzeug==0.16.0

